os: linux
language: python
python: "3.4" # dbus-python can not be built on higher versions of Python

addons:
  apt:
    packages:
      libdbus-glib-1-dev

branches:
    only: master

env:
  - TASK=fmt-travis
  - TASK=lint
  - TASK=test
  - TASK=coverage

script: make -f Makefile $TASK
